name: Conditional Builds Workflow

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.platform }} - ${{ matrix.buildType }}
    strategy:
      matrix:
        include:
          - platform: ubuntu-latest
            buildType: debug
            os: linux
          - platform: windows-latest
            buildType: release
            os: windows
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      
      - name: Build Debug on Linux
        if: matrix.os == 'linux' && matrix.buildType == 'debug'
        run: echo "Run Linux Debug specific commands"
        # Replace echo with your Linux debug build commands
      
      - name: Build Release on Windows
        if: matrix.os == 'windows' && matrix.buildType == 'release'
        run: echo "Run Windows Release specific commands"
        # Replace echo with your Windows release build commands
