name: Conditional Builds Workflow

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.arch }} - ${{ matrix.buildType }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
        buildType: [release]
        include:
          - os: ubuntu-latest
            goos: linux
            platform: linux
          - os: windows-latest
            goos: windows
            platform: windows
          - os: macos-latest
            goos: darwin
            platform: darwin
        # exclude:
          # Example: Exclude ARM builds on Windows
          # - os: windows-latest
          #   arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19'


      - name: Setup libappindicator3-dev for linux
        if: matrix.goos == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev

      - name: Set up QEMU and Docker Buildx (for ARM architecture)
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v1

      - name: Build
        run: |
          echo "Building for ${{ matrix.goos }}, ${{ matrix.arch }}, ${{ matrix.buildType }}"
          go build -o myapp-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.buildType }}

