name: Conditional Builds Workflow

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.arch }} - ${{ matrix.buildType }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-latest-xlarge]
        arch: [amd64, arm64]
        buildType: [release]
        include:
          - os: ubuntu-latest
            goos: linux
            platform: linux
          - os: windows-latest
            goos: windows
            platform: windows
          - os: macos-latest
            goos: darwin
            platform: darwin
          - os: macos-latest-xlarge
            goos: darwin
            platform: darwin
        exclude:
          # Example: Exclude ARM builds on Windows
          - os: macos-latest-xlarge
            arch: amd64
          - os: macos-latest
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '^1.19'

      - name: Setup libappindicator3-dev for linux
        if: matrix.goos == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev

      # - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
      #   if: matrix.arch == 'arm64' && !(matrix.os == 'ubuntu-latest')
      #   run: |
      #     mkdir -p ~/.docker/machine/cache
      #     curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
      #     brew install docker docker-machine
      #     docker-machine create --driver virtualbox default
      #     docker-machine start default
      #     eval $(docker-machine env default)

      - name: Set up QEMU and Docker Buildx (for ARM architecture)
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3.0.0

      - name: Build
        run: |
          echo "Building for ${{ matrix.goos }}, ${{ matrix.arch }}, ${{ matrix.buildType }}"
          go build -o myapp-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.buildType }} ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.buildType }}
          path: myapp-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.buildType }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ github.workspace }}/artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

